// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIStorage is a mock of IStorage interface.
type MockIStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIStorageMockRecorder
}

// MockIStorageMockRecorder is the mock recorder for MockIStorage.
type MockIStorageMockRecorder struct {
	mock *MockIStorage
}

// NewMockIStorage creates a new mock instance.
func NewMockIStorage(ctrl *gomock.Controller) *MockIStorage {
	mock := &MockIStorage{ctrl: ctrl}
	mock.recorder = &MockIStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStorage) EXPECT() *MockIStorageMockRecorder {
	return m.recorder
}

// FetchHarga mocks base method.
func (m *MockIStorage) FetchHarga(ctx context.Context) (*StorageEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchHarga", ctx)
	ret0, _ := ret[0].(*StorageEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchHarga indicates an expected call of FetchHarga.
func (mr *MockIStorageMockRecorder) FetchHarga(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchHarga", reflect.TypeOf((*MockIStorage)(nil).FetchHarga), ctx)
}
